# Generated by Django 5.2 on 2025-06-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Historial_medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vacuna', models.CharField(max_length=100)),
                ('tratamiento', models.TextField(max_length=100)),
                ('mascota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascota.mascota')),
            ],
        ),
    ]
