# Generated by Django 5.2 on 2025-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_alter_mascota_edad_alter_mascota_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('adopcion', 'Adopción'), ('adoptado', 'Adoptado')], default='adopcion', max_length=10),
        ),
    ]
