# Generated by Django 4.2.20 on 2025-06-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_perfil1_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vacuna', models.CharField(max_length=100)),
                ('tratamiento', models.TextField(max_length=100)),
                ('mascota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.mascota')),
            ],
        ),
    ]
